[package]
name = "micecat"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.13.0", features = ["bevy_pbr", "bevy_render", "bevy_winit",] }
bevy_ecs = "0.13.0"
bevy_xpbd_3d = "0.4.0"
bevy_fly_camera = "0.16.0"
bevy_mod_raycast = "0.18.0"